DEFINE
	FUNCTION DataQuality.DEV.Tests = () =>
	UNION (
		// Row counts - all tables must have data
		PQL.Assert.Tbl.ShouldHaveRows("Data Quality: MarvelFact has rows", 'MarvelFact'),
		PQL.Assert.Tbl.ShouldHaveRows("Data Quality: DateDim has rows", 'DateDim'),
		PQL.Assert.Tbl.ShouldHaveRows("Data Quality: AlignmentDim has rows", 'AlignmentDim'),
		PQL.Assert.Tbl.ShouldHaveRows("Data Quality: EyeColorDim has rows", 'EyeColorDim'),

		// Null checks - key columns must not be null
		PQL.Assert.Col.ShouldNotBeNull("Data Quality: MarvelFact[Name] is not null", 'MarvelFact'[Name]),
		PQL.Assert.Col.ShouldNotBeNull("Data Quality: MarvelFact[Appearances] is not null", 'MarvelFact'[Appearances]),
		PQL.Assert.Col.ShouldNotBeNull("Data Quality: MarvelFact[DateID] is not null", 'MarvelFact'[DateID]),
		PQL.Assert.Col.ShouldNotBeNull("Data Quality: MarvelFact[EyeID] is not null", 'MarvelFact'[EyeID]),
		PQL.Assert.Col.ShouldNotBeNull("Data Quality: MarvelFact[AlignmentID] is not null", 'MarvelFact'[AlignmentID]),

		// Range checks
		PQL.Assert.Col.ShouldBeNonNegative("Data Quality: Appearances is non-negative", 'MarvelFact'[Appearances]),

		// Text cleanliness
		PQL.Assert.Col.TextShouldBeTrimmed("Data Quality: MarvelFact[Name] has no leading/trailing spaces", 'MarvelFact'[Name]),

		// Uniqueness checks on dimension keys
		PQL.Assert.Col.ShouldBeDistinct("Data Quality: AlignmentDim[AlignmentID] is unique", 'AlignmentDim'[AlignmentID]),
		PQL.Assert.Col.ShouldBeDistinct("Data Quality: AlignmentDim[Alignment] is unique", 'AlignmentDim'[Alignment]),
		PQL.Assert.Col.ShouldBeDistinct("Data Quality: EyeColorDim[EyeID] is unique", 'EyeColorDim'[EyeID]),
		PQL.Assert.Col.ShouldBeDistinct("Data Quality: EyeColorDim[Eye Color] is unique", 'EyeColorDim'[Eye Color]),
		PQL.Assert.Col.ShouldBeDistinct("Data Quality: DateDim[DateID] is unique", 'DateDim'[DateID]),

		// No null/blank dimension labels
		PQL.Assert.Col.ShouldNotBeNullOrBlank("Data Quality: AlignmentDim[Alignment] has no null or blank values", 'AlignmentDim'[Alignment]),
		PQL.Assert.Col.ShouldNotBeNullOrBlank("Data Quality: EyeColorDim[Eye Color] has no null or blank values", 'EyeColorDim'[Eye Color]),

		// Referential integrity checks
		PQL.Assert.ShouldEqual("Data Quality: All MarvelFact.DateID values exist in DateDim", 0, COUNTROWS(FILTER('MarvelFact', ISBLANK(RELATED('DateDim'[DateID]))))),
		PQL.Assert.ShouldEqual("Data Quality: All MarvelFact.AlignmentID values exist in AlignmentDim", 0, COUNTROWS(FILTER('MarvelFact', ISBLANK(RELATED('AlignmentDim'[AlignmentID]))))),
		PQL.Assert.ShouldEqual("Data Quality: All MarvelFact.EyeID values exist in EyeColorDim", 0, COUNTROWS(FILTER('MarvelFact', ISBLANK(RELATED('EyeColorDim'[EyeID])))))
	)

EVALUATE DataQuality.DEV.Tests()
