table DateDim
	lineageTag: 864aaed1-9b52-4c91-a679-eee5e9ce61ea

	measure 'Date Filter' = ```
			
			VAR MinDate =
			    FORMAT ( MIN ( 'DateDim'[Date] ), "MMMM, YYYY" )
			VAR MaxDate =
			    FORMAT ( MAX ( 'DateDim'[Date] ), "MMMM, YYYY" )
			VAR SelDate =
			    SELECTEDVALUE ( 'DateDim'[Date], "X" )
			RETURN
			    IF (
			        SelDate = "X",
			        "between " & MinDate & " and " & MaxDate,
			        "for the month of " & FORMAT ( SelDate, "MMMM, YYYY" )
			    )
			
			```
		lineageTag: 4a102139-aa1e-4805-8ff3-8f26cc11ca77

	column DateID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: f04165d7-a964-463a-9fe1-11c45e755a75
		summarizeBy: none
		sourceColumn: DateID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1f5eadd5-60fa-4976-a5ef-a7abd80457b5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: string
		lineageTag: 99cbf526-ec1a-4670-b1ef-873cddd7efaa
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column MonthYearSort
		dataType: int64
		formatString: 0
		lineageTag: d0061923-ebd6-4cfd-be33-d910d8d0714f
		summarizeBy: none
		sourceColumn: MonthYearSort

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Month Year' = IF([DateID]<>0,FORMAT([Date],"MMM-YY"),"Not Available")
		lineageTag: 022b9561-6f1d-432a-927a-b431bbcc5cff
		summarizeBy: none
		sortByColumn: MonthYearSort

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 526e727b-b599-42fa-9aba-ff2c64b6c7df
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition DateDim-e3a1d953-1356-4aad-8dfb-22648d5b0c23 = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = MarvelSource,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"FIRST APPEARANCE", "Year"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Other Columns", "FIRST APPEARANCE", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"FIRST APPEARANCE.1", "FIRST APPEARANCE.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"FIRST APPEARANCE.1", type text}, {"FIRST APPEARANCE.2", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Date", each Date.FromText([FIRST APPEARANCE.1]&" 1, "&Text.From([Year]))),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([Date] <> null)),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows",{{"Date", Order.Ascending}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Sorted Rows",{"FIRST APPEARANCE.1", "FIRST APPEARANCE.2", "Year"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "EndDate", each Date.From(DateTime.LocalNow())),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom1", let earliest = List.Min(#"Added Custom1"[Date]) in each [Date] = earliest),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows1", {"Date"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"Date", "StartDate"}}),
				    #"Added Custom2" = Table.AddColumn(#"Renamed Columns", "Dates", each {Number.From([StartDate])..Number.From([EndDate])}),
				    #"Expanded Dates" = Table.ExpandListColumn(#"Added Custom2", "Dates"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Expanded Dates",{{"Dates", type date}}),
				    #"Filter1stMonth" = Table.SelectRows(#"Changed Type2", each Date.Day([Dates]) = 1),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filter1stMonth",{"StartDate", "EndDate"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Columns1", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Dates"}),
				    #"Added Custom3" = Table.AddColumn(#"Reordered Columns", "DateKey", each Date.ToText([Dates],"MMM-yyyy")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom3",{{"Dates", "Date"}, {"Index", "DateID"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns1", DateDimBlank}),
				    #"Sorted Rows1" = Table.Sort(#"Appended Query",{{"DateID", Order.Ascending}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Sorted Rows1","","Jan-0001",Replacer.ReplaceValue,{"DateKey"}),
				    #"Added Custom4" = Table.AddColumn(#"Replaced Value", "MonthYearSort", each Date.Year([Date])*100 + Date.Month([Date])),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Year", each Date.Year([Date])),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom5",{{"Year", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

