table MarvelFact
	lineageTag: 743cae73-8a6b-4e03-af99-d194d47d16af

	measure 'Number of Characters' = ```
			COUNTROWS('MarvelFact') + 10
			
			```
		formatString: 0
		lineageTag: df54ac01-57f7-4a28-a338-2609c59c6503

	measure 'Number of Characters Title By Date' = "Number of Characters that first appeared " & [Date Filter]
		lineageTag: 69d792e2-4fcc-4491-9f87-3ddb00d7bbbc

	measure 'Rank of Appearances' = ```
						
						RANKX (
			    ALLEXCEPT ( 'MarvelFact', AlignmentDim[Alignment] ),
			    CALCULATE ( SUM ( 'MarvelFact'[Appearances] ) )
			)
						
			```
		formatString: 0
		lineageTag: 714f1b79-a4f3-4a84-a723-7b62d9467ba9

	measure 'Running Total of Character Appearances' = ```
			
			CALCULATE (COUNTROWS ( 'MarvelFact' ),
			    FILTER (ALL ( 'MarvelFact' ),
			        'MarvelFact'[DateID] <= MAX ( 'DateDim'[DateID] ))
			)
			
			```
		formatString: #,0
		lineageTag: 7fb56eb7-be01-4955-92db-9dab09d95a7a

	column ID
		dataType: int64
		formatString: 0
		lineageTag: b7ff624e-3f51-4955-89fb-6129a2da0110
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: babc8e7f-21c5-43d2-b7f3-f871a5275156
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Appearances
		dataType: int64
		formatString: #,0
		lineageTag: 1eaca556-a316-4132-bec0-1e10537e8c5a
		summarizeBy: sum
		sourceColumn: Appearances

		annotation SummarizationSetBy = Automatic

	column DateID
		dataType: int64
		formatString: 0
		lineageTag: 5a5e1b5e-96a3-43c5-bfa1-dbf397dbe6dc
		summarizeBy: none
		sourceColumn: DateID

		annotation SummarizationSetBy = Automatic

	column EyeID
		dataType: int64
		formatString: 0
		lineageTag: e91d9d2a-fc21-45d6-b9a4-562098b146d3
		summarizeBy: none
		sourceColumn: EyeID

		annotation SummarizationSetBy = Automatic

	column AlignmentID
		dataType: int64
		formatString: 0
		lineageTag: 6cdf4368-853c-471f-8092-72f8e6ef6b29
		summarizeBy: none
		sourceColumn: AlignmentID

		annotation SummarizationSetBy = Automatic

	column 'Test Change' = 1
		dataType: dateTime
		formatString: Long Time
		lineageTag: 48b215f3-6230-4672-ae9f-8133298d5615
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition MarvelFact-6bd788f7-6397-4a40-bbcd-b7a7355b7188 = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = MarvelSource,
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"page_id", Int64.Type}, {"name", type text}, {"urlslug", type text}, {"ID", type text}, {"ALIGN", type text}, {"EYE", type text}, {"HAIR", type text}, {"SEX", type text}, {"GSM", type text}, {"ALIVE", type text}, {"APPEARANCES", Int64.Type}, {"FIRST APPEARANCE", type text}, {"Year", Int64.Type}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "FIRST APPEARANCE", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"FIRST APPEARANCE.1", "FIRST APPEARANCE.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"FIRST APPEARANCE.1", type text}, {"FIRST APPEARANCE.2", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "DateKey", each [FIRST APPEARANCE.1]&"-"&Text.From([Year])),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom",null,"Jan-0001",Replacer.ReplaceValue,{"DateKey"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"FIRST APPEARANCE.1", "FIRST APPEARANCE.2", "Year"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"DateKey"}, DateDim, {"DateKey"}, "DateDim", JoinKind.LeftOuter),
				    #"Expanded DateDim" = Table.ExpandTableColumn(#"Merged Queries", "DateDim", {"DateID"}, {"DateDim.DateID"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded DateDim",{"DateKey"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"DateDim.DateID", "DateID"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"SEX", "GSM", "ALIVE", "urlslug"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns2", {"EYE"}, EyeColorDim, {"EyeKey"}, "EyeColorDim", JoinKind.LeftOuter),
				    #"Expanded EyeColorDim" = Table.ExpandTableColumn(#"Merged Queries1", "EyeColorDim", {"EyeID"}, {"EyeID"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Expanded EyeColorDim",{"HAIR"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Columns3", {"ALIGN"}, AlignmentDim, {"AlignmentKey"}, "AlignmentDim", JoinKind.LeftOuter),
				    #"Expanded AlignmentDim" = Table.ExpandTableColumn(#"Merged Queries2", "AlignmentDim", {"AlignmentID"}, {"AlignmentID"}),
				    #"Removed Columns4" = Table.RemoveColumns(#"Expanded AlignmentDim",{"ID", "ALIGN", "EYE"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns4",{{"name", "Name"}, {"APPEARANCES", "Appearances"}, {"page_id", "ID"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

